# Generated by Django 3.2.3 on 2021-05-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('preview', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=11)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('preview', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='AeroCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='AeroDescription',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.description')),
            ],
            bases=('kvants.description',),
        ),
        migrations.CreateModel(
            name='AutoCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='AutoDescription',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.description')),
            ],
            bases=('kvants.description',),
        ),
        migrations.CreateModel(
            name='HiTechCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='HiTechDescription',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.description')),
            ],
            bases=('kvants.description',),
        ),
        migrations.CreateModel(
            name='ItCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='ItDescription',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.description')),
            ],
            bases=('kvants.description',),
        ),
        migrations.CreateModel(
            name='PromDesCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='PromDesDescription',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.description')),
            ],
            bases=('kvants.description',),
        ),
        migrations.CreateModel(
            name='PromRoboCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='PromRoboDescription',
            fields=[
                ('description_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.description')),
            ],
            bases=('kvants.description',),
        ),
    ]
