# Generated by Django 3.2 on 2021-05-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.CharField(max_length=300)),
                ('course_name', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=11)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AeroCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='AutoCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='ChessCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='HiTechCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='ItCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='MathCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='PromDesCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
        migrations.CreateModel(
            name='PromRoboCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kvants.course')),
            ],
            bases=('kvants.course',),
        ),
    ]
