# Generated by Django 3.2 on 2021-05-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvants', '0002_course_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module',
        ),
    ]
