# Generated by Django 3.2 on 2021-05-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvants', '0003_remove_course_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_link',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
