# Generated by Django 3.2 on 2021-05-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvants', '0005_course_choose_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='choose_course_link',
        ),
    ]
