# Generated by Django 3.2 on 2021-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvants', '0007_aerodescription_autodescription_chesscdescription_description_hitechdescription_itdescription_mathde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
