# Generated by Django 3.2 on 2021-05-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvants', '0009_description_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
